# Generated by Django 4.2 on 2023-04-29 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("department", "0002_alter_group_name_alter_teacher_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="subject",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="department.subject",
            ),
        ),
    ]
